### ISSUE TITLE
Standard AST across all statement types (v1.0.0)

### ISSUE THREAD

**Issue by nwronski** [codeschool/sqlite-parser#3]
- [x] **[In Progress]** Finish standardizing AST format across all types of statements
  - [x] `ORDER BY`
  - [x] `LIMIT`
  - [x] `name` property across node types
  - [ ] ~~`type` and `variant` combine into single `type` property~~ **Move to v2.0.0 milestone**
  - [x] `target`
- [x] **[DONE]** Organize tests and SQL test queries by type and split out into different files/directories.

**Comment by jdrew1303** [comment]
Hi @nwronski 

I was wondering if you were still working on standardising the node `type` and `variant`? I'm working on an AST walker based off the Estraverse code base and I've encountered some issue with nodes not having `types` on them (eg the `on` property).  I can bypass it if necessary but it slows walking down. Every key has to be visited and checked to see if there is an object or array to walk into instead of knowing in advance where it needs to go.

If you're not working on it would it be ok for me to submit pull requests to add types to the nodes? They will be quite simplistic to allow the walker to get up and running but I wouldnt mind working on the full refactor of `type` and `variant` if you could do with some help?
