### ISSUE TITLE
Node Structure Change: Add variant to module node of create virtual table statement.

### ISSUE THREAD

**Issue by jdrew1303** [codeschool/sqlite-parser#37]
![image](https://cloud.githubusercontent.com/assets/2535432/19889839/2e19fd4e-a02f-11e6-8681-aa89867008e9.png)

I found another node on my travels that needs some extra fields. This isn't too urgent, Ive a work around I'm using at the moment for some of the nodes.

![image](https://cloud.githubusercontent.com/assets/2535432/19890196/13f21b8e-a031-11e6-91a4-32bc8da3c32a.png)

**Comment by nwronski** [comment]
Originally, I tried to create the AST to contain the minimum amount of information required. So, if there was only one node that had a `type` of `module` then I wouldn't add a `variant` property since that would be redundant information. But, I see more value in keeping things consistent now, so that tools like yours can be made without having to handle tons of edge cases.
